In [1]:
import pandas as pd
import datetime
from minio import Minio

import sys
sys.path.append(r'D:\Documentos\Projetos\Ollist_End_to_End\airflow\dags')
from functions import var, read_minio_parquet

In [2]:
data_lake_server= var['data_lake_server_local']
data_lake_login= var['data_lake_login']
data_lake_password= var['data_lake_password']

client = Minio(
        endpoint= data_lake_server,
        access_key= data_lake_login,
        secret_key= data_lake_password,
        secure=False
    )

In [3]:
read_minio_parquet(bucket_name= 'agrupamento-clientes', file= 'dataframe_rfm.parquet', client= client)

                     customer_unique_id  frequency  monetary  recency
0      0000366f3b9a7992bf8c76cfdf3221e2          1    129.90    115.0
1      0000b849f77a49e4a4ce2b2a4ca5be3f          1     18.90    118.0
2      0000f46a3911fa3c0805444483337064          1     69.00    541.0
3      0000f6ccb0745a6a4b88665a16c9f078          1     25.99    325.0
4      0004aac84e0df4da2b147fca70cf8255          1    180.00    292.0
...                                 ...        ...       ...      ...
96091  fffcf5a5ff07b0908bd4e2dbc735a684          1   1570.00    451.0
96092  fffea47cd6d3cc0a88bd621562a9d061          1     64.89    266.0
96093  ffff371b4d645b6ecea244b27531430a          1     89.90    572.0
96094  ffff5962728ec6157033ef9805bacc48          1    115.00    123.0
96095  ffffd2657e2aad2907e67c3e9daecbeb          1     56.99    488.0

[96096 rows x 4 columns]